// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byokxwiunhzdsyulwxxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5b2t4d2l1bmh6ZHN5dWx3eHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTQyMTAsImV4cCI6MjA2MDc5MDIxMH0.zk3LJkeNg99CbqM2RW2Jl-5MhSmYIWf1WY5AnIU_paQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);